# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180228_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(max_length=200, null=True, verbose_name='订单留言'),
        ),
    ]
