# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180321_1549'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
